version: "3"
services: 
  tomcat:
    image: "tomcat:8"
    ports:
      - "8083-8085:8080"
    volumes:
      - "/mnt/myweb:/usr/local/tomcat/webapps"

  nginx:
    image: "nginx"
    ports: 
      - "90:80"
    volumes: 
      - "/mnt/html:/usr/share/nginx/html" 
