version: "3"
services: 
  tomcat:
    image: "tomcat:8"
    ports:
      - "8083-8085:8080-8082"
    volumes:
      - "/mnt/myweb:/usr/local/tomcat/webapps"

  nginx:
    image: "nginx"
    ports: 
      - "80=80"
    volumes: 
      - "/mnt/html:/var/www/html
    

   
